version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postegres_db_CESIZen
    restart: always
    environment:
      POSTGRES_USER: CesiZenAdm
      POSTGRES_PASSWORD: CesiZenAdm59!
      POSTGRES_DB: CesiZenDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cesizen

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend/publish:/app
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postegres_db_CESIZen;Port=5432;Database=CesiZenDB;Username=CesiZenAdm;Password=CesiZenAdm59!
    depends_on:
      - postgres
    networks:
      - cesizen
    command: ["dotnet", "Backend.dll"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:80"
    environment:
      - API_URL=/api
    volumes:
      - static_assets:/usr/share/nginx/html/assets
    depends_on:
      - backend
    networks:
      - cesizen

volumes:
  postgres_data:
  static_assets:

networks:
  cesizen:
    external: true
