version: '3.8'

services:
  postgres-prod:
    image: postgres:latest
    container_name: postegres_db_CESIZen_prod
    restart: always
    environment:
      POSTGRES_USER: CesiZenAdm
      POSTGRES_PASSWORD: CesiZenAdm59!
      POSTGRES_DB: CesiZenDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - backend-prod
      - traefik

  backend-prod:
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    container_name: backend-prod
    working_dir: /app
#    volumes:
#      - ./backend/publish:/app
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postegres_db_CESIZen;Port=5432;Database=CesiZenDB;Username=CesiZenAdm;Password=CesiZenAdm59!
    depends_on:
      - postgres-prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`rasphubert.ddns.net`) && PathPrefix(`/emilien-prod/api`)"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/emilien-prod/api"
      - "traefik.http.routers.api.middlewares=api-strip"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
    networks:
      - backend-prod
      - traefik
    command: ["dotnet", "Backend.dll"]



  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-prod
    expose:
      - "4000"  # SSR Angular écoute ici
    depends_on:
      - backend-prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`rasphubert.ddns.net`) && PathPrefix(`/emilien-prod`)"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=le"
    networks:
      - frontend-prod
      - traefik

volumes:
  postgres_prod_data:

networks:
  backend-prod:
  frontend-prod:
  traefik:
    external: true
