version: '3.8'

services:
  postgres-prod:
    image: postgres:latest
    container_name: postgres_db_CESIZen_prod
    restart: always
    environment:
      POSTGRES_USER: CesiZenAdm
      POSTGRES_PASSWORD: CesiZenAdm59!
      POSTGRES_DB: CesiZenDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - backend-prod-emilien
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U CesiZenAdm"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend-prod:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    container_name: backend-prod
    working_dir: /app
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres-prod;Port=5432;Database=CesiZenDB;Username=CesiZenAdm;Password=CesiZenAdm59!
    depends_on:
      - postgres-prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-prod.rule=Host(`rasphubert.ddns.net`) && PathPrefix(`/emilien-prod/api`)"
      - "traefik.http.middlewares.api-prod-strip.stripprefix.prefixes=/emilien-prod/api"
      - "traefik.http.routers.api-prod.middlewares=api-prod-strip"
      - "traefik.http.services.api-prod.loadbalancer.server.port=5000"
      - "traefik.http.routers.api-prod.entrypoints=websecure"
      - "traefik.http.routers.api-prod.tls.certresolver=le"
    networks:
      - backend-prod-emilien
      - traefik
    command: ["dotnet", "Backend.dll"]

  frontend-prod:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        DEPLOY_ENV: production
        BASE_HREF: /emilien-prod/
    container_name: frontend-prod
    ports:
      - "4001:80"  # Nginx écoute sur le port 80
    environment:
      - API_URL=/emilien-prod/api
    depends_on:
      - backend-prod
    restart: unless-stopped
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-prod.rule=Host(`rasphubert.ddns.net`) && PathPrefix(`/emilien-prod`)"
      - "traefik.http.services.front-prod.loadbalancer.server.port=80"
      - "traefik.http.routers.front-prod.entrypoints=websecure"
      - "traefik.http.routers.front-prod.tls.certresolver=le"
    networks:
      - frontend-prod-emilien
      - traefik

volumes:
  postgres_prod_data:

networks:
  backend-prod-emilien:
  frontend-prod-emilien:
  traefik:
    external: true